name: "Build"
on:
  push:
    branches:
      - statediff
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: run dapp tests
#        run: nix-env -iA nixpkgs.bashInteractive && nix-shell --pure src/dapp-tests/shell.nix --command 'make --directory src/dapp-tests'
      - name: Get the version
        id: vars
        run: echo ::set-output name=sha::$(echo ${GITHUB_SHA:0:7})
      - name: Run docker build
        run: make docker-build
      - name: Tag docker image
        run: docker tag vulcanize/dapptools docker.pkg.github.com/vulcanize/dapptools/dapptools:${{steps.vars.outputs.sha}}
      - name: Docker Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u vulcanize --password-stdin
      - name: Docker Push
        run: docker push docker.pkg.github.com/vulcanize/dapptools/dapptools:${{steps.vars.outputs.sha}}
