name: "Build"
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@63cf434de4e4292c6960639d56c5dd550e789d77
        with:
          # we use the nixpkgs defined in default.nix
          skip_adding_nixpkgs_channel: false
      - name: run dapp tests
        run: nix-env -iA nixpkgs.bashInteractive && nix-shell --pure src/dapp-tests/shell.nix --command 'make --directory src/dapp-tests'
      - name: Run docker build
        run: make docker-build
